### ISSUE TITLE
Data not Syncing since 7/9/2024 - 500 error code (Reddit API User endpoint Issue)

### ISSUE THREAD

**Issue by DnanaDev** [aplotor/expanse#49]
Noticed that the app stopped syncing data a few days ago. There seems to be an error when fetching the about section for a user. Possibly the Reddit API removed access to this endpoint? 
I tried logging in again and doesn't seem like my app credentials are the issue. 

App logs below:
      ```socket (NdmCmwMtSnlsympqAAAL) connected
getting user (<Redacted>)
deserialized user (<Redacted>)
getting user (<Redacted>)
update all started
getting user (<Redacted>)
updating user (<Redacted>)
StatusCodeError: 500 - "<html>\n  <head>\n    <title>reddit broke!</title>\n  </head>\n  <body>\n    <div style=\"margin: auto; text-align: center\">\n      <p>\n        <a href=\"/\">\n          <img border=\"0\" src=\"//www.redditstatic.com/youbrokeit1.png\" alt=\"you broke reddit\" />\n        </a>\n      </p>\n    </div>\n  </body>\n</html>\n"
    at new StatusCodeError (/app/backend/node_modules/request-promise-core/lib/errors.js:32:15)
    at /app/backend/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/app/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/app/backend/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/app/backend/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/app/backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/backend/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/app/backend/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21) {
  statusCode: 500,
  error: '<html>\n' +
    '  <head>\n' +
    '    <title>reddit broke!</title>\n' +
    '  </head>\n' +
    '  <body>\n' +
    '    <div style="margin: auto; text-align: center">\n' +
    '      <p>\n' +
    '        <a href="/">\n' +
    '          <img border="0" src="//www.redditstatic.com/youbrokeit1.png" alt="you broke reddit" />\n' +
    '        </a>\n' +
    '      </p>\n' +
    '    </div>\n' +
    '  </body>\n' +
    '</html>\n',
  options: {
    gzip: true,
    json: true,
    headers: { 'user-agent': 'web:expanse:v=1.2.9 (hosted by u/<Redacted>)' },
    baseUrl: 'https://oauth.reddit.com',
    qs: { raw_json: 1 },
    auth: {
      bearer: '<Redacted>'
    },
    resolveWithFullResponse: true,
    timeout: 30000,
    transform: [Function: transform],
    uri: 'u/bonniealex/about',
    callback: [Function: RP$callback],
    simple: true,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: false,
      ended: true,
      endEmitted: true,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: true
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'oauth.reddit.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'oauth.reddit.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 30000,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 21736,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 496490,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 21756,
        [Symbol(triggerId)]: 21745
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 2274,
      [Symbol(kBytesWritten)]: 1141,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
      'Connection',
      'close',
      'content-type',
      'text/html; charset=UTF-8',
      'x-ua-compatible',
      'IE=edge',
      'x-ratelimit-used',
      '92',
      'x-ratelimit-remaining',
      '908.0',
      'x-ratelimit-reset',
      '369',
      'content-encoding',
      'gzip',
      'Accept-Ranges',
      'bytes',
      'Date',
      'Mon, 09 Sep 2024 09:33:51 GMT',
      'Via',
      '1.1 varnish',
      'Vary',
      'Accept-Encoding',
      'Strict-Transport-Security',
      'max-age=31536000; includeSubdomains',
      'X-Content-Type-Options',
      'nosniff',
      'X-Frame-Options',
      'SAMEORIGIN',
      'X-XSS-Protection',
      '1; mode=block',
      'Set-Cookie',
      'loid=<Redacted>; Domain=reddit.com; Max-Age=63071999; Path=/; expires=Wed, 09-Sep-2026 09:33:51 GMT; secure; SameSite=None; Secure',
      'Set-Cookie',
      'session_tracker=<redacted>; Domain=reddit.com; Max-Age=7199; Path=/; expires=Mon, 09-Sep-2024 11:33:51 GMT; secure; SameSite=None; Secure',
      'Set-Cookie',
      'csv=2; Max-Age=63072000; Domain=.reddit.com; Path=/; Secure; SameSite=None',
      'Set-Cookie',
      'edgebucket=wnRnbEBB6A9j1bMtQ6; Domain=reddit.com; Max-Age=63071999; Path=/;  secure',
      'Cache-Control',
      'private, max-age=3600',
      'Server',
      'snooserv',
      'Report-To',
      '{"group": "w3-reporting-nel", "max_age": 14400, "include_subdomains": true,  "endpoints": [{ "url": "https://w3-reporting-nel.reddit.com/reports" }]}, {"group": "w3-reporting", "max_age": 14400, "include_subdomains": true, "endpoints": [{ "url": "https://w3-reporting.reddit.com/reports" }]}, {"group": "w3-reporting-csp", "max_age": 14400, "include_subdomains": true, "endpoints": [{ "url": "https://w3-reporting-csp.reddit.com/reports" }]}',
      'NEL',
      '{"report_to": "w3-reporting-nel", "max_age": 14400, "include_subdomains": false, "success_fraction": 1.0, "failure_fraction": 1.0}',
      'transfer-encoding',
      'chunked'
    ],
    rawTrailers: [],
    joinDuplicateHeaders: undefined,
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 500,
    statusMessage: 'Internal Server Error',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'oauth.reddit.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'oauth.reddit.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 30000,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 21736,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 496490,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 21756,
        [Symbol(triggerId)]: 21745
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 2274,
      [Symbol(kBytesWritten)]: 1141,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: true,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /u/bonniealex/about?raw_json=1 HTTP/1.1\r\n' +
        'user-agent: web:expanse:v=1.2.9 (hosted by u/<Redacted>)\r\n' +
        'host: oauth.reddit.com\r\n' +
        'authorization: Bearer <Redacted>\r\n' +
        'accept-encoding: gzip, deflate\r\n' +
        'accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/u/bonniealex/about?raw_json=1',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'oauth.reddit.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      gzip: true,
      headers: [Object],
      resolveWithFullResponse: true,
      timeout: 30000,
      transform: [Function: transform],
      uri: [Url],
      readable: true,
      writable: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise [Object]],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      method: 'GET',
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'oauth.reddit.com',
      url: [Url],
      path: '/u/bonniealex/about?raw_json=1',
      _json: true,
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://oauth.reddit.com/u/bonniealex/about?raw_json=1',
      req: [ClientRequest],
      ntick: true,
      timeoutTimer: null,
      response: [Circular *1],
      originalHost: 'oauth.reddit.com',
      originalHostHeaderName: 'host',
      responseContent: [Gunzip],
      _ended: true,
      _destdata: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '<html>\n' +
      '  <head>\n' +
      '    <title>reddit broke!</title>\n' +
      '  </head>\n' +
      '  <body>\n' +
      '    <div style="margin: auto; text-align: center">\n' +
      '      <p>\n' +
      '        <a href="/">\n' +
      '          <img border="0" src="//www.redditstatic.com/youbrokeit1.png" alt="you broke reddit" />\n' +
      '        </a>\n' +
      '      </p>\n' +
      '    </div>\n' +
      '  </body>\n' +
      '</html>\n',
    [Symbol(kCapture)]: false,
    [Symbol(kHeaders)]: {
      connection: 'close',
      'content-type': 'text/html; charset=UTF-8',
      'x-ua-compatible': 'IE=edge',
      'x-ratelimit-used': '92',
      'x-ratelimit-remaining': '908.0',
      'x-ratelimit-reset': '369',
      'content-encoding': 'gzip',
      'accept-ranges': 'bytes',
      date: 'Mon, 09 Sep 2024 09:33:51 GMT',
      via: '1.1 varnish',
      vary: 'Accept-Encoding',
      'strict-transport-security': 'max-age=31536000; includeSubdomains',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'set-cookie': [Array],
      'cache-control': 'private, max-age=3600',
      server: 'snooserv',
      'report-to': '{"group": "w3-reporting-nel", "max_age": 14400, "include_subdomains": true,  "endpoints": [{ "url": "https://w3-reporting-nel.reddit.com/reports" }]}, {"group": "w3-reporting", "max_age": 14400, "include_subdomains": true, "endpoints": [{ "url": "https://w3-reporting.reddit.com/reports" }]}, {"group": "w3-reporting-csp", "max_age": 14400, "include_subdomains": true, "endpoints": [{ "url": "https://w3-reporting-csp.reddit.com/reports" }]}',
      nel: '{"report_to": "w3-reporting-nel", "max_age": 14400, "include_subdomains": false, "success_fraction": 1.0, "failure_fraction": 1.0}',
      'transfer-encoding': 'chunked'
    },
    [Symbol(kHeadersCount)]: 48,
    [Symbol(kTrailers)]: null,
    [Symbol(kTrailersCount)]: 0
  }
}
update all completed```

**Comment by DnanaDev** [comment]
Looks like a Reddit Issue. 

Some relevant discussion for the about page here :
https://www.reddit.com/r/redditdev/comments/1f9z9yo/uusername_endpoint_broken/

**Comment by DnanaDev** [comment]
Fixed by Reddit.
